bhagatprasad/HealthSysHub

- HealthSysHub.Web.API/Controllers/WeatherForecastController.cs
- HealthSysHub.Web.API/HealthSysHub.Web.API.csproj
- HealthSysHub.Web.API/HealthSysHub.Web.API.http
- HealthSysHub.Web.API/Program.cs
- HealthSysHub.Web.API/Properties/launchSettings.json
- HealthSysHub.Web.API/WeatherForecast.cs
- HealthSysHub.Web.API/appsettings.Development.json
- HealthSysHub.Web.API/appsettings.json
- HealthSysHub.Web.DB/HealthSysHub.Web.DB.sqlproj
- HealthSysHub.Web.Tests/HealthSysHub.Web.Tests.csproj
- HealthSysHub.Web.Tests/UnitTest1.cs
- HealthSysHub.Web.Utility/Class1.cs
- HealthSysHub.Web.Utility/HealthSysHub.Web.Utility.csproj
- HealthSysHub.sln
> creating required projects

- HealthSysHub.Web.API/Controllers/RoleController.cs
- HealthSysHub.Web.API/HealthSysHub.Web.API.csproj
- HealthSysHub.Web.API/Program.cs
- HealthSysHub.Web.API/Startup.cs
- HealthSysHub.Web.API/appsettings.json
- HealthSysHub.Web.DB/HealthSysHub.Web.DB.sqlproj
- HealthSysHub.Web.DB/Post-Deployment/SeedSpecialization.sql
- HealthSysHub.Web.DBConfiguration/ApplicationDBContext.cs
- HealthSysHub.Web.DBConfiguration/HealthSysHub.Web.DBConfiguration.csproj
- HealthSysHub.Web.DBConfiguration/Models/Department.cs
- HealthSysHub.Web.DBConfiguration/Models/LabTest.cs
- HealthSysHub.Web.DBConfiguration/Models/Medicine.cs
- HealthSysHub.Web.DBConfiguration/Models/PatientType.cs
- HealthSysHub.Web.DBConfiguration/Models/PaymentType.cs
- HealthSysHub.Web.DBConfiguration/Models/Specialization.cs
- HealthSysHub.Web.DataManagers/Class1.cs
- HealthSysHub.Web.DataManagers/HealthSysHub.Web.DataManagers.csproj
- HealthSysHub.Web.DataManagers/RoleDataManager.cs
- HealthSysHub.Web.Managers/Class1.cs
- HealthSysHub.Web.Managers/HealthSysHub.Web.Managers.csproj
- HealthSysHub.Web.Managers/IRoleManager.cs
- HealthSysHub.Web.MicroServices/HealthSysHub.Web.MicroServices.csproj
- HealthSysHub.Web.Utility/HealthSysHub.Web.Utility.csproj
- HealthSysHub.Web.Utility/Helpers/EntityUpdater.cs
> db related changes

- HealthSysHub.Web.MicroServices/Functions/Department/DepartmentFunctions.cs
- HealthSysHub.Web.MicroServices/Functions/Department/GetDepartmentById.cs
- HealthSysHub.Web.MicroServices/Functions/Department/GetDepartments.cs
- HealthSysHub.Web.MicroServices/Functions/Department/InsertOrUpdateDepartment.cs
- HealthSysHub.Web.MicroServices/Functions/HospitalType/GetHospitalTypeById.cs
- HealthSysHub.Web.MicroServices/Functions/HospitalType/GetHospitalTypes.cs
- HealthSysHub.Web.MicroServices/Functions/HospitalType/HospitalTypeFunctions.cs
- HealthSysHub.Web.MicroServices/Functions/HospitalType/InsertOrUpdateHospitalType.cs
- HealthSysHub.Web.MicroServices/Functions/LabTest/GetLabTestById.cs
- HealthSysHub.Web.MicroServices/Functions/LabTest/GetLabTests.cs
- HealthSysHub.Web.MicroServices/Functions/LabTest/InsertOrUpdateLabTest.cs
- HealthSysHub.Web.MicroServices/Functions/LabTest/LabTestFunctions.cs
- HealthSysHub.Web.MicroServices/Functions/Medicine/MedicineFunctions.cs
- HealthSysHub.Web.MicroServices/Functions/PatientType/PatientTypeFunctions.cs
- HealthSysHub.Web.MicroServices/Functions/PaymentType/PaymentTypeFunctions.cs
- HealthSysHub.Web.MicroServices/Functions/Role/RoleFunctions.cs
- HealthSysHub.Web.MicroServices/HealthSysHub.Web.MicroServices.csproj
- HealthSysHub.Web.MicroServices/Program.cs
Microservices configuration best practices focus on maintaining flexibility and scalability. Key strategies include avoiding hardcoded values, using distributed configuration management, and ensuring each microservice has its own data store to enhance security and reduce latency. ### Configuration Management
Environment Variables: Load configuration settings into environment variables to keep sensitive information out of the codebase.
External Configuration: Use external configuration management tools like Consul or Spring Cloud Config to manage configurations centrally.
Secrets Management: Store sensitive information such as API keys and passwords in a secure vault (e.g., HashiCorp Vault) rather than hardcoding them.
Service Discovery
Service Registry: Implement a service registry (e.g., …
> micro services configuratiion

- HealthSysHub.Web.API/Controllers/DoctorAppointmentController.cs
- HealthSysHub.Web.API/Startup.cs
- HealthSysHub.Web.DB/HealthSysHub.Web.DB.sqlproj
- HealthSysHub.Web.DB/Tables/DoctorAppointment.sql
- HealthSysHub.Web.DBConfiguration/ApplicationDBContext.cs
- HealthSysHub.Web.DBConfiguration/Models/DoctorAppointment.cs
- HealthSysHub.Web.DataManagers/DoctorAppointmentDataManager.cs
- HealthSysHub.Web.Managers/IDoctorAppointmentManager.cs
- HealthSysHub.Web.UI/Controllers/DoctorAppointmentController.cs
- HealthSysHub.Web.UI/Controllers/ReceptionistDashboardController.cs
- HealthSysHub.Web.UI/Interfaces/IDoctorAppointmentService.cs
- HealthSysHub.Web.UI/Models/DoctorAppointment.cs
- HealthSysHub.Web.UI/Services/DoctorAppointmentService.cs
- HealthSysHub.Web.UI/Startup.cs
- HealthSysHub.Web.UI/Views/DoctorAppointment/Index.cshtml
- HealthSysHub.Web.UI/Views/ReceptionistDashboard/Index.cshtml
- HealthSysHub.Web.UI/wwwroot/js/DynamicSideBarController.js
- HealthSysHub.Web.UI/wwwroot/js/ReceptionistDashboardController.js
- HealthSysHub.Web.Utility/Models/DoctorAppointmentDetails.cs
Constructor: Initializes the controller with the required services for handling doctor appointments and notifications.
Index Method: Returns the main view for the doctor appointments.
GetDoctorAppointmentsAsync: Retrieves a list of doctor appointments based on the hospital ID and optional date, returning a JSON response.
GetDoctorAppointmentByIdAsync: Fetches a specific appointment by its ID and returns the result in JSON format.
InsertOrUpdateDoctorAppointment: Accepts a doctor appointment object, processes it, and returns the result as JSON.
DeleteDoctorAppointmentAsync: Deletes an appointment by its ID and returns a status code indicating success or failure.
GetActiveDoctorAppointmentsAsync: Retrieves active appointments for a specified hospital and returns the data in JSON format. …
> Constructor: Initializes the controller with the required services for handling doctor appointments and notifications.

- HealthSysHub.Web.DBConfiguration/Models/Doctor.cs
- HealthSysHub.Web.DBConfiguration/Models/Nurse.cs
- HealthSysHub.Web.DBConfiguration/Models/PatientCare.cs
- HealthSysHub.Web.DBConfiguration/Models/Receptionist.cs
- HealthSysHub.Web.DataManagers/DoctorAppointmentDataManager.cs
- HealthSysHub.Web.UI/Controllers/DoctorDashboardController.cs
- HealthSysHub.Web.UI/Models/Doctor.cs
- HealthSysHub.Web.UI/Views/DoctorAppointment/_insertOrUpdateDoctorAppointmentPartial.cshtml
- HealthSysHub.Web.UI/Views/DoctorDashboard/ManageDoctorAppointments.cshtml
- HealthSysHub.Web.UI/Views/Shared/_gridHeaderPartial.cshtml
- HealthSysHub.Web.UI/wwwroot/assets/css/style.css
- HealthSysHub.Web.UI/wwwroot/js/AccountController.js
- HealthSysHub.Web.UI/wwwroot/js/CommonController.js
- HealthSysHub.Web.UI/wwwroot/js/DoctorAppointmentController.js
- HealthSysHub.Web.UI/wwwroot/js/DoctorDashboardController.js
Insert or update doctor oppoeintment
> Insert or update doctor oppoeintment

- HealthSysHub.Web.UI/Services/UserService.cs
- HealthSysHub.Web.UI/Views/Shared/_gridHeaderPartial.cshtml
- HealthSysHub.Web.UI/wwwroot/assets/css/sidebar.css
- HealthSysHub.Web.UI/wwwroot/assets/css/style.css
- HealthSysHub.Web.UI/wwwroot/js/CommonController.js
- HealthSysHub.Web.UI/wwwroot/js/DoctorAppointmentController.js
- HealthSysHub.Web.UI/wwwroot/js/UserController.js
doctor appointment grid and slider mobile verson
> doctor appointment grid and slider mobile verson

- HealthSysHub.Web.API/Controllers/DoctorController.cs
- HealthSysHub.Web.API/Startup.cs
- HealthSysHub.Web.DataManagers/DoctorDataManager.cs
- HealthSysHub.Web.Managers/IDoctorManager.cs
- HealthSysHub.Web.UI/Controllers/ReportController.cs
- HealthSysHub.Web.UI/Services/DoctorService.cs
- HealthSysHub.Web.UI/Startup.cs
- HealthSysHub.Web.UI/wwwroot/assets/css/style.css
- HealthSysHub.Web.UI/wwwroot/js/DoctorAppointmentController.js
doctor functionality and invoice genarator
> doctor functionality and invoice genarator

- HealthSysHub.Web.API/Controllers/DoctorAppointmentController.cs
- HealthSysHub.Web.DataManagers/DoctorAppointmentDataManager.cs
- HealthSysHub.Web.Managers/IDoctorAppointmentManager.cs
- HealthSysHub.Web.UI/Controllers/DepartmentController.cs
- HealthSysHub.Web.UI/Controllers/DoctorAppointmentController.cs
- HealthSysHub.Web.UI/Controllers/DoctorDashboardController.cs
- HealthSysHub.Web.UI/Controllers/HomeController.cs
- HealthSysHub.Web.UI/Controllers/HospitalController.cs
- HealthSysHub.Web.UI/Controllers/HospitalTypeController.cs
- HealthSysHub.Web.UI/Controllers/LabTestController.cs
- HealthSysHub.Web.UI/Controllers/MedicineController.cs
- HealthSysHub.Web.UI/Controllers/PatientTypeController.cs
- HealthSysHub.Web.UI/Controllers/PaymentTypeController.cs
- HealthSysHub.Web.UI/Controllers/ReceptionistDashboardController.cs
- HealthSysHub.Web.UI/Controllers/ReportController.cs
- HealthSysHub.Web.UI/Controllers/RoleController.cs
- HealthSysHub.Web.UI/Controllers/SpecializationController.cs
- HealthSysHub.Web.UI/Controllers/StaffController.cs
- HealthSysHub.Web.UI/Controllers/UserController.cs
- HealthSysHub.Web.UI/Interfaces/IDoctorAppointmentService.cs
- HealthSysHub.Web.UI/Models/PrintAppointmentsReportRequest.cs
- HealthSysHub.Web.UI/Services/DoctorAppointmentService.cs
- HealthSysHub.Web.UI/wwwroot/js/DoctorAppointmentController.js
- HealthSysHub.Web.Utility/Models/PrintAppointmentsReportRequest.cs
> dotcot appointments

- HealthSysHub.Web.DataManagers/ConsultationDataManager.cs
- HealthSysHub.Web.MicroServices/HealthSysHub.Web.MicroServices.csproj
- HealthSysHub.Web.UI/Controllers/ConsultationController.cs
- HealthSysHub.Web.UI/Views/DoctorAppointment/_insertOrUpdateDoctorAppointmentPartial.cshtml
- HealthSysHub.Web.UI/wwwroot/js/DoctorAppointmentController.js
- HealthSysHub.Web.UI/wwwroot/js/DoctorDashboardController.js
code changes for consulation form
> code changes for consulation form

- HealthSysHub.Web.DataManagers/ConsultationDataManager.cs
- HealthSysHub.Web.UI/Controllers/DoctorDashboardController.cs
- HealthSysHub.Web.UI/Views/DoctorDashboard/ManageConsultationAppointment.cshtml
- HealthSysHub.Web.UI/wwwroot/js/DoctorAppointmentController.js
- HealthSysHub.Web.UI/wwwroot/js/DoctorDashboardController.js
- HealthSysHub.Web.UI/wwwroot/js/ManageConsultationAppointmentController.js
> display consulation details

- HealthSysHub.Web.DataManagers/ConsultationDataManager.cs
- HealthSysHub.Web.UI/Views/DoctorDashboard/ManageConsultationAppointment.cshtml
- HealthSysHub.Web.UI/wwwroot/js/ManageConsultationAppointmentController.js
Feature/bind consulation data UI
> Feature/bind consulation data UI

- HealthSysHub.Web.API/Controllers/LabOrderRequestController.cs
- HealthSysHub.Web.API/Startup.cs
- HealthSysHub.Web.DataManagers/LabOrderRequestDataManager.cs
- HealthSysHub.Web.Managers/IConsultationManager.cs
- HealthSysHub.Web.Managers/ILabOrderRequestManager.cs
- HealthSysHub.Web.UI/Controllers/LabOrderRequestController.cs
- HealthSysHub.Web.UI/Interfaces/ILabOrderRequestService.cs
- HealthSysHub.Web.UI/Services/LabOrderRequestService.cs
- HealthSysHub.Web.UI/Startup.cs
- HealthSysHub.Web.UI/Views/DoctorDashboard/ManageConsultationAppointment.cshtml
- HealthSysHub.Web.UI/Views/Shared/_LabTestInventoryPopUp.cshtml
- HealthSysHub.Web.UI/Views/Shared/_MedicineInventoryPopUp.cshtml
- HealthSysHub.Web.UI/wwwroot/assets/css/style.css
- HealthSysHub.Web.UI/wwwroot/js/LabTestInventoryController.js
- HealthSysHub.Web.UI/wwwroot/js/ManageConsultationAppointmentController.js
- HealthSysHub.Web.UI/wwwroot/js/MedicineInventoryController.js
- HealthSysHub.Web.Utility/Models/LabOrderRequestDetails.cs
- HealthSysHub.Web.Utility/Models/LabOrderRequestItemDetails.cs
> Lab Request Order Process

- HealthSysHub.Web.API/Controllers/PharmacyOrderRequestController.cs
- HealthSysHub.Web.API/Startup.cs
- HealthSysHub.Web.DBConfiguration/Models/PharmacyOrderRequestItem.cs
- HealthSysHub.Web.DataManagers/PharmacyOrderRequestDataManager.cs
- HealthSysHub.Web.Managers/IPharmacyOrderRequestManager.cs
- HealthSysHub.Web.UI/Controllers/PharmacyOrderRequestController.cs
- HealthSysHub.Web.UI/Interfaces/IPharmacyOrderRequestService.cs
- HealthSysHub.Web.UI/Services/PharmacyOrderRequestService.cs
- HealthSysHub.Web.UI/Startup.cs
- HealthSysHub.Web.UI/wwwroot/js/CommonController.js
- HealthSysHub.Web.UI/wwwroot/js/ManageConsultationAppointmentController.js
- HealthSysHub.Web.UI/wwwroot/js/MedicineInventoryController.js
- HealthSysHub.Web.Utility/Models/PharmacyOrderRequestDetails.cs
- HealthSysHub.Web.Utility/Models/PharmacyOrderRequestItemDetails.cs
> Pharmacy Order Request

- HealthSysHub.Web.DataManagers/ConsultationDataManager.cs
- HealthSysHub.Web.UI/Views/DoctorDashboard/ManageConsultationAppointment.cshtml
- HealthSysHub.Web.UI/wwwroot/js/DoctorDashboardController.js
- HealthSysHub.Web.UI/wwwroot/js/ManageConsultationAppointmentController.js
> Doctor Consulation submited

- HealthSysHub.Web.API/Controllers/LabController.cs
- HealthSysHub.Web.API/Controllers/LabStaffController.cs
- HealthSysHub.Web.API/Controllers/PharmacyController.cs
- HealthSysHub.Web.API/Controllers/PharmacyStaffController.cs
- HealthSysHub.Web.API/Startup.cs
- HealthSysHub.Web.DB/HealthSysHub.Web.DB.sqlproj
- HealthSysHub.Web.DB/Tables/Lab.sql
- HealthSysHub.Web.DB/Tables/LabStaff.sql
- HealthSysHub.Web.DB/Tables/Pharmacy.sql
- HealthSysHub.Web.DB/Tables/PharmacyStaff.sql
- HealthSysHub.Web.DB/Tables/User.sql
- HealthSysHub.Web.DBConfiguration/ApplicationDBContext.cs
- HealthSysHub.Web.DBConfiguration/Models/Lab.cs
- HealthSysHub.Web.DBConfiguration/Models/LabStaff.cs
- HealthSysHub.Web.DBConfiguration/Models/Pharmacy.cs
- HealthSysHub.Web.DBConfiguration/Models/PharmacyStaff.cs
- HealthSysHub.Web.DBConfiguration/Models/User.cs
- HealthSysHub.Web.DataManagers/AuthenticationDataManager.cs
- HealthSysHub.Web.DataManagers/LabDataManager.cs
- HealthSysHub.Web.DataManagers/LabStaffDataManager.cs
- HealthSysHub.Web.DataManagers/PharmacyDataManager.cs
- HealthSysHub.Web.DataManagers/PharmacyStaffDataManager.cs
- HealthSysHub.Web.Managers/ILabManager.cs
- HealthSysHub.Web.Managers/ILabStaffManager.cs
- HealthSysHub.Web.Managers/IPharmacyManager.cs
- HealthSysHub.Web.Managers/IPharmacyStaffManager.cs
- HealthSysHub.Web.Utility/Models/ApplicationUser.cs
land and phamcry staff on boarding
> land and phamcry staff on boarding

- HealthSysHub.Web.API/Controllers/PharmacyMedicineController.cs
- HealthSysHub.Web.API/Controllers/PharmacyOrderRequestController.cs
- HealthSysHub.Web.API/Startup.cs
- HealthSysHub.Web.DB/HealthSysHub.Web.DB.sqlproj
- HealthSysHub.Web.DB/Tables/PharmacyMedicine.sql
- HealthSysHub.Web.DB/Tables/PharmacyOrder.sql
- HealthSysHub.Web.DB/Tables/PharmacyOrderItem.sql
- HealthSysHub.Web.DB/Tables/PharmacyOrderRequest.sql
- HealthSysHub.Web.DB/Tables/PharmacyOrderRequestItem.sql
- HealthSysHub.Web.DBConfiguration/ApplicationDBContext.cs
- HealthSysHub.Web.DBConfiguration/Models/PharmacyMedicine.cs
- HealthSysHub.Web.DBConfiguration/Models/PharmacyOrder.cs
- HealthSysHub.Web.DBConfiguration/Models/PharmacyOrderItem.cs
- HealthSysHub.Web.DBConfiguration/Models/PharmacyOrderRequest.cs
- HealthSysHub.Web.DBConfiguration/Models/PharmacyOrderRequestItem.cs
- HealthSysHub.Web.DataManagers/PharmacyMedicineDataManager.cs
- HealthSysHub.Web.DataManagers/PharmacyOrderDataManager.cs
- HealthSysHub.Web.DataManagers/PharmacyOrderRequestDataManager.cs
- HealthSysHub.Web.Managers/IPharmacyMedicineManager.cs
- HealthSysHub.Web.Managers/IPharmacyOrderManager.cs
- HealthSysHub.Web.Managers/IPharmacyOrderRequestManager.cs
- HealthSysHub.Web.Utility/Models/PharmacyOrderDetails.cs
- HealthSysHub.Web.Utility/Models/PharmacyOrderItemDetails.cs
- HealthSysHub.Web.Utility/Models/PharmacyOrderRequestDetails.cs
- HealthSysHub.Web.Utility/Models/PharmacyOrderRequestItemDetails.cs
> phamrcy related changes

- HealthSysHub.Web.API/Controllers/OrderController.cs
- HealthSysHub.Web.DataManagers/PharmacyOrderDataManager.cs
- HealthSysHub.Web.DataManagers/PharmacyOrderRequestDataManager.cs
- HealthSysHub.Web.Managers/IPharmacyOrderManager.cs
- HealthSysHub.Web.Utility/Models/PharmacyOrdersProcessRequest.cs
- HealthSysHub.Web.Utility/Models/PharmacyOrdersProcessResponse.cs
Here's the optimized version of your method with improved performance, cleaner code, and better practices:
```csharp
public async Task<List<PharmacyOrderDetails>> GetPharmacyOrdersListByPharmacyAsync(Guid pharmacyId)
{
// Load all required data in parallel
var (orders, requests, requestItems, medicines) = await (
_dbContext.pharmacyOrders
.Where(o => o.PharmacyId == pharmacyId)
.ToListAsync(),
_dbContext.pharmacyOrderRequests
.Where(r => r.PharmacyId == pharmacyId)
.ToListAsync(),
_dbContext.pharmacyOrderRequestItems
.Where(i => i.PharmacyId == pharmacyId)
.ToListAsync(),
_dbContext.pharmacyMedicines
.Where(m => m.PharmacyId == pharmacyId)
.ToListAsync()
);
if (!orders.Any())
{
return new List<PharmacyOrderDetails>();
}
// Create lookup dictionaries for faster access
var requestsLookup = …
```
> Here's the optimized version of your method with improved performance, cleaner code, and better practices:

- HealthSysHub.Web.API/Controllers/OrderController.cs
- HealthSysHub.Web.DataManagers/PharmacyOrderDataManager.cs
- HealthSysHub.Web.Pharmacy.UI/src/app/app.routes.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/models/pharmacy-order-details.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/models/pharmacy-order-item-details.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/models/pharmacy-orders-process-request.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/models/pharmacy-orders-process-response.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/models/pharmacyorder.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/models/processpharmacyorderrequest.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/models/processpharmacyorderrequestresponse.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/orders/list.component.css
- HealthSysHub.Web.Pharmacy.UI/src/app/orders/list.component.html
- HealthSysHub.Web.Pharmacy.UI/src/app/orders/list.component.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/services/order.service.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/services/pharmacy-order-request-service.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/services/shared.module.ts
- HealthSysHub.Web.Pharmacy.UI/src/environment.ts
Here's the complete HTML table with enhanced display of order items in a list format and all other columns properly formatted:
```html
<table class="table table-bordered table-hover">
<thead class="thead-dark" style="background-color: gray;">
<tr>
<th>Patient Name</th>
<th>Order Ref</th>
<th>Contact</th>
<th>Doctor</th>
<th>Medications</th>
<th>Created</th>
<th>Modified</th>
<th>Status</th>
<th>Active</th>
<th>Total</th>
<th>Actions</th>
</tr>
</thead>
<tbody>
<tr *ngFor="let request of pharmacyOrderDetails">
<td>
<a class="btn-link font-weight-bold" (click)="pharmacyOrderDetails(request)">
{{ request.name || 'N/A' }}
</a>
</td>
<td class="text-monospace small">{{ request.orderReference || 'N/A' }}</td>
<td>{{ request.phone || 'N/A' }}</td>
<td>{{ request.doctorName || 'N/A' }}</td>
<td> …
```
> Here's the complete HTML table with enhanced display of order items in a list format and all other columns properly formatted:

- HealthSysHub.Web.API/Controllers/OrderController.cs
- HealthSysHub.Web.API/Controllers/PharmacyPaymentController.cs
- HealthSysHub.Web.API/Startup.cs
- HealthSysHub.Web.DB/Tables/PharmacyPayment.sql
- HealthSysHub.Web.DataManagers/PharmacyOrderDataManager.cs
- HealthSysHub.Web.DataManagers/PharmacyOrderRequestDataManager.cs
- HealthSysHub.Web.DataManagers/PharmacyPaymentDataManager.cs
- HealthSysHub.Web.Managers/IPharmacyOrderManager.cs
- HealthSysHub.Web.Managers/IPharmacyPaymentManager.cs
- HealthSysHub.Web.Pharmacy.UI/src/app/app.routes.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/models/pharmacy-payment-detail.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/models/pharmacy-payment.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/orders/list.component.html
- HealthSysHub.Web.Pharmacy.UI/src/app/orders/list.component.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/services/payment.service.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/services/shared.module.ts
- HealthSysHub.Web.Pharmacy.UI/src/app/shared/popups/paynow.component.css
- HealthSysHub.Web.Pharmacy.UI/src/app/shared/popups/paynow.component.html
- HealthSysHub.Web.Pharmacy.UI/src/app/shared/popups/paynow.component.ts
- HealthSysHub.Web.Pharmacy.UI/src/environment.ts
- HealthSysHub.Web.Utility/Models/PharmacyPaymentDetail.cs
Here are both the complete HTML and TypeScript files for your PayNow component with all the requested functionality:
```html
<div class="modal-overlay" *ngIf="isOpen" (click)="close()">
<div class="modal-content" (click)="$event.stopPropagation()">
<div class="modal-header">
<h3>Pay now</h3>
<button class="close-btn" (click)="close()">
<i class="mdi mdi-close"></i>
</button>
</div>
<div class="modal-body">
<form [formGroup]="paymentForm" (ngSubmit)="confirm()">
<div class="form-group">
<label for="paymentMethod">Payment Method*</label>
<div class="input-group">
<span class="input-group-text">
<i class="mdi mdi-cash"></i>
</span>
<select class="form-control" id="paymentMethod" formControlName="paymentMethod" required>
<option value="" disabled selected>Select payment method</option> …
```
> Here are both the complete HTML and TypeScript files for your PayNow component with all the requested functionality:

- HealthSysHub.Web.Pharmacy.UI/.angular/cache/19.2.8/HealthSysHub.Web.Pharmacy.UI/vite/deps/@angular_core.js
- HealthSysHub.Web.Pharmacy.UI/.angular/cache/19.2.8/HealthSysHub.Web.Pharmacy.UI/vite/deps/@angular_platform-browser.js
- HealthSysHub.Web.Pharmacy.UI/.angular/cache/19.2.8/HealthSysHub.Web.Pharmacy.UI/vite/deps/@angular_router.js
- HealthSysHub.Web.Pharmacy.UI/.angular/cache/19.2.8/HealthSysHub.Web.Pharmacy.UI/vite/deps/_metadata.json
- HealthSysHub.Web.Pharmacy.UI/.angular/cache/19.2.8/HealthSysHub.Web.Pharmacy.UI/vite/deps_ssr/@angular_core.js
- HealthSysHub.Web.Pharmacy.UI/.angular/cache/19.2.8/HealthSysHub.Web.Pharmacy.UI/vite/deps_ssr/@angular_platform-browser.js
- HealthSysHub.Web.Pharmacy.UI/.angular/cache/19.2.8/HealthSysHub.Web.Pharmacy.UI/vite/deps_ssr/@angular_platform-server.js
- HealthSysHub.Web.Pharmacy.UI/.angular/cache/19.2.8/HealthSysHub.Web.Pharmacy.UI/vite/deps_ssr/@angular_router.js
- HealthSysHub.Web.Pharmacy.UI/.angular/cache/19.2.8/HealthSysHub.Web.Pharmacy.UI/vite/deps_ssr/@angular_ssr.js
- HealthSysHub.Web.Pharmacy.UI/.angular/cache/19.2.8/HealthSysHub.Web.Pharmacy.UI/vite/deps_ssr/@angular_ssr_node.js
- HealthSysHub.Web.Pharmacy.UI/.angular/cache/19.2.8/HealthSysHub.Web.Pharmacy.UI/vite/deps_ssr/_metadata.json
- HealthSysHub.Web.Pharmacy.UI/angular.json
- HealthSysHub.Web.Pharmacy.UI/node_modules/.package-lock.json
- HealthSysHub.Web.Pharmacy.UI/package-lock.json
- HealthSysHub.Web.Pharmacy.UI/package.json
- HealthSysHub.Web.Pharmacy.UI/src/app/dashboard/admin/admin.component.html
Based on your `angular.json`, your project is configured for **SSR (Server-Side Rendering)**. Since GitHub Pages only supports static files, we need to modify the configuration. Here's the complete procedure:
---
```bash
cd E:\HealthSysHub\HealthSysHub.Web.Pharmacy.UI
del server.ts src/main.server.ts tsconfig.server.json
```
```bash
npm remove @angular/ssr
```
Remove SSR-related configurations:
```json
"server": "src/main.server.ts",
"outputMode": "server",
"ssr": {
"entry": "src/server.ts"
}
```
Change the **builder** from:
```json
"builder": "@angular-devkit/build-angular:application"
```
to:
```json
"builder": "@angular-devkit/build-angular:browser"
```
---
```bash
rmdir /s /q dist node_modules
npm install
```
---
```bash
ng build --configuration=production --base-href /HealthSysHub/ …
```
> # **Step-by-Step Guide to Deploy Your Angular 19 App to GitHub Pages**

- healthsyshub.web.ip.ui/public/index.html
- healthsyshub.web.ip.ui/src/App.vue
- healthsyshub.web.ip.ui/src/components/common/Navbar.vue
> sidebar and navbar configure

- healthsyshub.web.ip.ui/package.json
- healthsyshub.web.ip.ui/src/App.vue
- healthsyshub.web.ip.ui/src/components/auth/Login.vue
- healthsyshub.web.ip.ui/src/components/common/Header.vue
- healthsyshub.web.ip.ui/src/components/common/Navbar.vue
- healthsyshub.web.ip.ui/src/global/API/auth.service.js
- healthsyshub.web.ip.ui/src/main.js
- healthsyshub.web.ip.ui/src/router/index.js
- healthsyshub.web.ip.ui/src/stores/auth.store.js
- healthsyshub.web.ip.ui/yarn.lock
Here's your updated login form with a show/hide password toggle feature:
```html
<template>
<div class="auth-wrapper">
<div class="auth-content text-center">
<div class="card borderless">
<div class="row align-items-center">
<div class="col-md-12">
<div class="card-body">
<h4 class="mb-3 f-w-400">Sign in</h4>
<hr>
<form @submit.prevent="handleLogin">
<div class="form-group mb-3">
<input type="username" class="form-control" id="username"
placeholder="username/phone" v-model="credentials.username" required>
</div>
<div class="form-group mb-4">
<div class="input-group">
<input 
:type="showPassword ? 'text' : 'password'" 
class="form-control" 
id="Password" 
placeholder="*******"
v-model="credentials.password" 
required
>
<div class="input-group-append">
<span class="input-group-text" …
```
> Here's your updated login form with a show/hide password toggle feature:

- HealthSysHub.Web.API/Controllers/BedsController.cs
- HealthSysHub.Web.API/Startup.cs
- HealthSysHub.Web.DB/HealthSysHub.Web.DB.sqlproj
- HealthSysHub.Web.DB/Tables/Bed.sql
- HealthSysHub.Web.DBConfiguration/ApplicationDBContext.cs
- HealthSysHub.Web.DBConfiguration/Models/Bed.cs
- HealthSysHub.Web.DataManagers/BedDataManager.cs
- HealthSysHub.Web.Managers/IBedManager.cs
1. Interface (IBedManager)
2. Data Manager (BedDataManager)
3. API Controller (BedsController)
```csharp
public interface IBedManager
{
Task<Bed> GetBedByIdAsync(Guid bedId);
Task<List<Bed>> GetBedsByRoomAsync(Guid roomId);
Task<List<Bed>> GetAvailableBedsAsync(Guid? roomId = null, string? bedType = null);
Task<Bed> CreateBedAsync(Bed bed);
Task<Bed> UpdateBedAsync(Guid bedId, Bed bed, Guid modifiedBy);
Task<bool> UpdateBedOccupancyAsync(Guid bedId, bool isOccupied, Guid modifiedBy);
Task<bool> UpdateBedStatusAsync(Guid bedId, bool isActive, Guid modifiedBy);
}
```
```csharp
public class BedDataManager : IBedManager
{
private readonly ApplicationDBContext _dbContext;
private readonly ILogger<BedDataManager> _logger;
public BedDataManager(ApplicationDBContext dbContext, …
```
> Here's the complete implementation for the `Bed` entity, including:
